# Common rule for web nodes.
#
# Notes:
# - Tasks marked with tag 'auto' are executed automatically by schedule, others - on demand
- name: Create directory structure for Filebeat
  win_file:
    path: D:\Beats\
    state: directory
  tags:
    - filebeat
    - filebeat_create_dir

- name: Download Filebeat
  win_get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-windows-x86_64.zip
    dest: D:\Beats\filebeat-{{ filebeat_version }}-windows-x86_64.zip

- name: Unzip Filebeat
  win_unzip:
    src: D:\Beats\filebeat-{{ filebeat_version }}-windows-x86_64.zip
    dest: D:\Beats\
    delete_archive: yes

- name: Copy folder Filebeat
  win_copy:
    src: D:\Beats\filebeat-{{ filebeat_version }}-windows-x86_64
    dest: D:\Beats\filebeat

- name: Remove directory structure
  win_file:
    path: D:\Beats\filebeat-{{ filebeat_version }}-windows-x86_64
    state: absent