# Common rule for web nodes.
#
# Notes:
# - Tasks marked with tag 'auto' are executed automatically by schedule, others - on demand
- name: Create directory structure for Filebeat
  win_file:
    path: D:\Beats\
    state: directory
  tags:
    - filebeat
    - filebeat_create_dir

- name: Download Filebeat
  win_get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-windows-x86_64.zip
    dest: D:\Beats\filebeat-{{ filebeat_version }}-windows-x86_64.zip
    force: no

- name: Unzip Filebeat
  win_unzip:
    src: D:\Beats\filebeat-{{ filebeat_version }}-windows-x86_64.zip
    dest: D:\Beats\
    #delete_archive: yes

- name: Obtain information about a folder
  win_stat:
    path: 'D:\Beats\filebeat'
  register: folder_stat

- name: rename the filebeat
  win_command: "cmd.exe /c rename D:\\Beats\\filebeat-{{ filebeat_version }}-windows-x86_64 filebeat"
  when: folder_stat.stat.exists == False

- name: Create directory data, logs
  win_file:
    path: D:\Beats\filebeat\{{ item }}
    state: directory
  with_items:
    - 'data'
    - 'logs'
  tags:
    - filebeat
    - filebeat_create_dir

- name: Change line workdir folder in instal script
  win_lineinfile:
     path: 'D:\Beats\filebeat\install-service-filebeat.ps1'
     regexp: '^(.*")C:\\ProgramData(.*)$'
     backrefs: yes
     line: '$1$workdir$2'

