# Common rule for web nodes.
#
# Notes:
# - Tasks marked with tag 'auto' are executed automatically by schedule, others - on demand
- name: Copy sitecore_master_index
  win_copy:
    src: '{{ solr_root }}\apache-solr\solr\sitecore_master_index'
    dest: d:\temp\
    remote_src: True
  tags: never, r11

- name: Remove folders in data folder
  win_file:
    path: 'd:\temp\sitecore_master_index\data\{{ item }}'
    state: absent
  with_items:
    - 'index'
    - 'tlog'
  tags: never, r11

- name: Copy a folder sitecore_master_index to new index
  win_copy:
    src: 'd:\temp\sitecore_master_index\'
    dest: 'd:\temp\{{ item }}\'
    remote_src: True
  with_items:
    - 'article_master_index'
    - 'article_web_index'
    - 'shop_catalog_master_index'
    - 'shop_catalog_web_index'
  tags: never, r11

- name: Change core settings
  win_lineinfile:
    path: 'd:\temp\{{ item }}\core.properties'
    regexp: '^name='
    line: 'name={{ item }}'
  with_items:
    - 'article_master_index'
    - 'article_web_index'
    - 'shop_catalog_master_index'
    - 'shop_catalog_web_index'
  tags: never, r11

- name: Copy new sitecore index to solr folder
  win_copy:
    src: 'd:\temp\{{ item }}'
    dest: '{{ solr_root }}\apache-solr\solr\'
    remote_src: True
    force: no
  with_items:
    - 'article_master_index'
    - 'article_web_index'
    - 'shop_catalog_master_index'
    - 'shop_catalog_web_index'
  tags: never, r11
